# workflow for building and deploying to GitHub Pages
name: Deploy Hugo site to Pages
 
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
 
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
 
# Default to bash
defaults:
  run:
    shell: bash
 
# Environment variables available to all jobs and steps in this workflow
env:
  HUGO_ENV: production
  HUGO_VERSION: "0.141.0"
  GO_VERSION: "1.23.3"
 
jobs:
  # Build job
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-arm64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
 
      - name: Install Go
        run: |
          wget -O ${{ runner.temp }}/go.deb https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz \
          && sudo tar -C /usr/local -xzf ${{ runner.temp }}/go.deb
 
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
          fetch-depth: 0
 
      - name: Setup Project
        run: cd hugoplate-main && npm run project-setup
 
      - name: Install npm dependencies
        run: cd hugoplate-main && npm install
 
      - name: Build site
        run: cd hugoplate-main && npm run build
 
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './hugoplate-main/public'
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
